task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('home2', views.home, name='home2'),
    path('', views.authentication, name='home'),
    path('authentication', views.authentication, name='authentication'),
    path('registration', views.registration, name='registration'),
    path('logout', views.logout_view, name='logout'),
    path('cabinet/', views.cabinet, name='cabinet'),
    path('cabinet/edit/', views.edit_profile, name='edit_profile'),
    path('registration/manager/', views.registration_manager, name='registration_manager'),
    path('examplare', views.examplare, name='examplare'),
    path('create_project/', views.create_project, name='create_project'),
    path('company_dashboard/', views.company_dashboard, name='company_dashboard'),
    path('developer_dashboard/', views.developer_dashboard, name='developer_dashboard'),
    path('create_task/<int:project_id>/', views.create_task, name='create_task'),
    path('project_detail/<int:project_id>/', views.project_detail, name='project_detail'),
    path('task_detail/<int:task_id>/', views.task_detail, name='task_detail'),
    path('notifications/', views.notifications, name='notifications'),
    path('send_completed_task/<int:task_id>/', views.send_completed_task, name='send_completed_task'),
    path('view_completed_tasks/', views.view_completed_tasks, name='view_completed_tasks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskandvacation/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('', include('vacation.urls')),
]

task/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
import uuid

class Manager(AbstractUser):
    ava_image = models.ImageField(upload_to='avatars/', default='avatars/default_avatar.png')
    name = models.CharField( verbose_name='Название Компании', max_length=255)
    def __str__(self):
        return self.name
    company_identifier = models.CharField(verbose_name='Идентификатор Компании', max_length=255)
    def __str__(self):
        return self.company_identifier
    status = models.IntegerField(choices=((1, 'Developer'),(2, 'Company')), default=1)

class Project(models.Model):
    user = models.ForeignKey(Manager, on_delete=models.CASCADE)
    name_project = models.CharField(verbose_name='Название проекта', max_length=255)
    description_project = models.CharField(verbose_name='Описание проекта', max_length=1000)
    start_date = models.DateField()
    end_date = models.DateField()


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assigned_developer = models.ForeignKey(Manager, on_delete=models.SET_NULL, null=True, blank=True)
    name_task = models.CharField(verbose_name='Название задачи', max_length=255)
    description_task = models.CharField(verbose_name='Описание задачи', max_length=1000)
    difficulty_level = models.IntegerField(choices=((1, 'Легкий'),(2, 'Средний'), (3, 'Сложный')), default=1)
    start_date = models.DateField()
    end_date = models.DateField()

    def create_notification(self, message):
        Notification.objects.create(user=self.assigned_developer, message=message)


@receiver(post_save, sender=Task)
def task_created_notification(sender, instance, created, **kwargs):
    if created and instance.assigned_developer:
        instance.create_notification(f"Создана новая задача: {instance.name_task}")


class Notification(models.Model):
    user = models.ForeignKey(Manager, on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message


class CompletedTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    sender = models.ForeignKey(Manager, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='completed_tasks/', blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Отправитель: {self.sender.username}"  # Возвращаем логин отправителя

task/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.detail import SingleObjectMixin
from datetime import date
from task.forms import *
from .models import Notification


def home(request):
    return render(request, 'task/home2.html')

def examplare(request):
    return render(request, 'task/examplare.html')

def registration(request):
    if request.method == 'POST':
        form = CustomDeveloperCreationForm(request.POST)
        if form.is_valid():
            developer = form.save(commit=False)
            developer.status = 1  # Устанавливаем статус "Разработчик"

            if developer.status == 1:  # Если статус "Разработчик"
                similar_companies = Manager.objects.filter(company_identifier__iexact=developer.company_identifier)
                if similar_companies.exists():
                    company = similar_companies.first()
                    developer.name = company.name  # Устанавливаем name
                    developer.save()
                else:
                    messages.error(request, 'Нет похожих компаний. Напишите правильный идентификатор.')
                    return render(request, 'task/registration.html', {'form': form})
            login(request, developer)
            return redirect('developer_dashboard')
        else:
            print("Form is not valid. Errors:", form.errors)
    else:
        form = CustomDeveloperCreationForm()
    return render(request, 'task/registration.html', {'form': form})


def registration_manager(request):
    if request.method == 'POST':
        form = CustomManagerCreationForm(request.POST, exclude_company_identifier=True)
        if form.is_valid():
            manager = form.save(commit=False)
            manager.status = 2  # Устанавливаем статус "Компания"
            manager.company_identifier = str(uuid.uuid4())
            manager.save()
            login(request, manager)
            print("Manager saved successfully.")
            return redirect('company_dashboard')
        else:
            print("Form is not valid. Errors:", form.errors)
    else:
        form = CustomManagerCreationForm(exclude_company_identifier=True)
    return render(request, 'task/registration_manager.html', {'form': form})


def authentication(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            if user.status == 2:
                login(request, user)
                return redirect('company_dashboard')
            if user.status == 1:
                login(request, user)
                return redirect('developer_dashboard')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'task/authentication.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('/')

@login_required
def cabinet(request):
    user = request.user  # Получить текущего пользователя
    return render(request, 'task/cabinet.html', {'user': user,})

@login_required
def edit_profile(request):
    user = request.user

    if request.method == 'POST':
        form = UserEditForm(request.POST,request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('cabinet')

    else:
        form = UserEditForm(instance=user)

    return render(request, 'task/edit_profile.html', {'form': form})

@login_required
def create_project(request):
    if request.user.status == 2:  # Проверка статуса "Company"
        if request.method == 'POST':
            form = ProjectForm(request.POST)
            if form.is_valid():
                project = form.save(commit=False)
                project.user = request.user
                project.save()
                return redirect('company_dashboard')
        else:
            form = ProjectForm()

        return render(request, 'task/create_project.html', {'form': form})
    else:
        # Обработка случая, когда пользователь не является компанией
        return redirect('developer_dashboard')  # Подстройте имя URL для разработчиков

@login_required
def create_task(request, project_id):
    project = get_object_or_404(Project, id=project_id, user=request.user)
    company_identifier = request.user.company_identifier  # Assuming the company identifier is stored in the user object
    if request.method == 'POST':
        form = TaskForm(request.POST, company_identifier=company_identifier)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project
            task.save()
            return redirect('company_dashboard')
    else:
        form = TaskForm(company_identifier=company_identifier)

    return render(request, 'task/create_task.html', {'form': form, 'project': project})

@login_required
def company_dashboard(request):
    user = request.user
    projects = Project.objects.filter(user=user)

    active_projects = []
    expiring_projects = []
    overdue_projects = []

    for project in projects:
        today = date.today()
        if project.end_date < today:
            project.status = 'overdue'
            overdue_projects.append(project)
        elif (project.end_date - today).days >= 4:
            project.status = 'active'
            active_projects.append(project)
        else:
            project.status = 'expiring'
            expiring_projects.append(project)

    return render(request, 'task/company_dashboard.html', {'active_projects': active_projects,
                                                           'expiring_projects': expiring_projects,
                                                           'overdue_projects': overdue_projects})

@login_required
def developer_dashboard(request):
    user = request.user
    tasks = Task.objects.filter(assigned_developer=user)

    active_tasks = []
    expiring_tasks = []
    overdue_tasks = []

    today = date.today()

    for task in tasks:
        if task.end_date < today:
            task.status = 'overdue'
            overdue_tasks.append(task)
        elif (task.end_date - today).days >= 4:
            task.status = 'active'
            active_tasks.append(task)
        else:
            task.status = 'expiring'
            expiring_tasks.append(task)

    return render(request, 'task/developer_dashboard.html', {'active_tasks': active_tasks,
                                                             'expiring_tasks': expiring_tasks,
                                                             'overdue_tasks': overdue_tasks})
@login_required
def project_detail(request, project_id):
    project = get_object_or_404(Project, id=project_id, user=request.user)
    return render(request, 'task/project_detail.html', {'project': project})

@login_required
def task_detail(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    user = request.user

    # Проверяем, является ли текущий пользователь разработчиком или компанией
    if user.status == 1 and task.assigned_developer == user:
        # Если пользователь - разработчик и это его задача
        return render(request, 'task/task_detail.html', {'task': task})
    elif user.status == 2 and task.project.user == user:
        # Если пользователь - компания и задача связана с ее проектом
        return render(request, 'task/task_detail.html', {'task': task})
    else:
        # В противном случае, если пользователь не имеет доступа, можно
        # либо показать ошибку, либо перенаправить на другую страницу
        return HttpResponseForbidden("У вас нет прав для просмотра этой задачи")


@login_required
def notifications(request):
    # Получаем все уведомления для текущего пользователя
    user_notifications = Notification.objects.filter(user=request.user).order_by('-timestamp')

    # Если у вас есть дополнительные логики для фильтрации уведомлений (например, показывать только непрочитанные),
    # добавьте соответствующую логику здесь.

    # Помечаем уведомления как прочитанные (по желанию)
    user_notifications.update(is_read=True)

    return render(request, 'task/notifications.html', {'notifications': user_notifications})

@login_required
def send_completed_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.method == 'POST':
        form = CompletedTaskForm(request.POST, request.FILES)
        if form.is_valid():
            completed_task = form.save(commit=False)
            completed_task.task = task
            completed_task.sender = request.user
            completed_task.save()
            return redirect('developer_dashboard')
    else:
        form = CompletedTaskForm()

    return render(request, 'task/send_completed_task.html', {'form': form, 'task': task})

@login_required
def view_completed_tasks(request):
    completed_tasks = CompletedTask.objects.filter(task__project__user=request.user)
    return render(request, 'task/view_completed_tasks.html', {'completed_tasks': completed_tasks})

task/templates/task/authentication.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Пример верстки</title>
    <link rel="stylesheet" href="../../static/task/css/styles3.css">
</head>
<body>
<header>
    <div class="header-content">
        <span>Узнать больше о нашем приложении ⟶</span>
        <a href="#" class="highlighted-text">ВОЗМОЖНОСТИ</a>
    </div>
</header>
<div class="form-container">
    <div class="custom2-image">
        <img src="../../static/task/img/111.png" alt="Картинка слева">
    </div>
        <div class="logo">
            <img src="../../static/task/img/Logo.svg" alt="Логотип">
        </div>
        <div class="spacer"></div>
        <h3>Авторизация</h3>
        <form method="POST">
            {% csrf_token %}
            <div class="input-group">
                <label for="username">Имя пользователя</label>
                {{ form.username }}
                {{ form.username.errors }}
            </div>
            <div class="input-group">
                <label for="password">Пароль</label>
                {{ form.password }}
                {{ form.password.errors }}
            </div>
            <button type="submit">Войти</button>
        </form>

        <div class="register-link">
            <span>Нет аккаунта?</span>
            <a href="{% url 'registration' %}">Создать аккаунт</a>
        </div>
        <div class="custom-image">
            <img src="../../static/task/img/123123.png" alt="Картинка справа">
        </div>
</body>
</html>

task/templates/task/base.html
{% load static %}

<head>
    <link rel="stylesheet" href="../../static/task/css/styles2.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <div class="logo">
        <img src="../../static/task/img/Logo.svg   " alt="Your Logo" class="logo">
    </div>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'cabinet' %}">Личный кабинет</a></li>
            {% if user.status == 1 %}
            <li><a href="{% url 'developer_dashboard' %}">Задачи</a></li>
            {% elif user.status == 2 %}
            <li><a href="{% url 'company_dashboard' %}">Проекты и задачи</a></li>
            {% endif %}
            <li><a href="{% url 'notifications' %}">Уведомления</a></li>
            <li><a href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
            <li><a href="#possibilities">Возможности</a></li>
            <li><a href="#solutions">Решения</a></li>
            <li><a href="#plans">Планы</a></li>
            <li><a href="#support">Поддержка</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

{% block content %}{% endblock %}

{% block additional_body %}{% endblock %}


<script>
        const inputFields = document.querySelectorAll('.input-container input');

        inputFields.forEach(inputField => {
            inputField.addEventListener('input', function () {
                const label = this.nextElementSibling; // Select the label

                if (this.value.trim() !== '') {
                    label.classList.add('hidden');
                } else {
                    label.classList.remove('hidden');
                }
            });
        });

</script>
</body>
</html>

task/templates/task/base3.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'task/css/styles.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Task and Vacation</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-bars"></i> Меню
                    </a>
                    <div class="dropdown-menu dropdown-menu-right rounded-0" aria-labelledby="navbarDropdown">
                        <!-- Здесь добавьте ссылки на страницы, связанные с проектами -->
                        <a class="dropdown-item" href="{% url 'cabinet' %}">Личный кабинет</a>
                        {% if user.status == 1 %}
                            <a class="dropdown-item" href="{% url 'developer_dashboard' %}">Задачи</a>
                        {% elif user.status == 2 %}
                            <a class="dropdown-item" href="{% url 'company_dashboard' %}">Проекты и задачи</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                        <!-- ... -->
                    </div>
                </li>
            {% else %}
                <li class="nav-item" style="margin-right: 10px;"><a href="{% url 'authentication' %}" class="nav-link active" aria-current="page">Войти</a></li>
                <li class="nav-item" style="margin-right: 10px;"><a href="{% url 'registration' %}" class="nav-link active" aria-current="page">Регистрация</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<!-- Your content goes here -->
{% block content %}{% endblock %}
<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>


../../static/task/js/basajs.js
../../static/task/css/basaStyles.css

task/templates/task/base5.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Webpage</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: 'Arial', sans-serif;
      display: flex;
      align-items: flex-start;
      height: 100vh;
      background-color: #232333;
    }

    .container {
      display: flex;
      flex-direction: row;
      justify-content: flex-start;
      align-items: flex-start;
    }

    .section1 {
      background-color: #2B2C40;
      width: 250px;
      height: 800px;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
      position: relative;
      margin-right: 13px; /* Отступ между блоками */
    }

    .section1 img {
      width: 240px;
      height: 45px;
      position: absolute;
      top: 5%;
      left: 50%;
      transform: translate(-50%, -50%);
    }

    .button {
      position: absolute;
      top: 80px;
      left: 50%;
      transform: translateX(-50%);
      border-radius: 5px;
      background-color: #696CFF;
      display: flex;
      align-items: center;
      cursor: pointer;
      width: 240px;
      border: none;
    }

    .button img {
      width: 20px;
      height: 20px;
      position: relative;
    }

    .button img:first-child {
      left: 10px; /* Отступ слева для первой картинки */
      top: 12px;
    }

    .button img:last-child {
      top:12px;
      margin-left: auto; /* Отступ справа для второй картинки */
    }

    .button span {
      font-size: 20px;
      font-weight: bold;
      color: white;
      margin: 0 auto; /* Центрирование текста */
    }

    .section2 {
      margin-top: 11px;
      background-color: #2B2C40;
      width: 1200px;
      height: 60px;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
      border-radius: 10px;
      display: flex;
      align-items: center;
    }

    .section2 img {
      width: 20px;
      height: 20px;
      margin-left: 20px;
    }

    .section2 p {
      margin-left: 10px;
      font-size: 24px;
      color: #A3A4CC;
    }

    .section2 .icons {
      margin-left: auto;
      display: flex;
    }

    .section2 .icons img {
      width: 25px;
      height: 25px;
      margin-right: 20px;
      margin-left: -5px;
      border-radius: 50%
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="section1">
      <img src="../../static/task/img/logo2.png" alt="Your Image">
      <button class="button">
        <div class="img">
          <img src="../../static/task/img/projects.png" alt="Icon">
          <span>Проекты</span>
          <img src="../../static/task/img/arrow.png" alt="Another Icon">
        </div>
      </button>
      <button class="button" style="margin-top: 30px;">
        <div class="img">
          <img src="../../static/task/img/projects.png" alt="Icon">
          <span>Задачи</span>
          <img src="../../static/task/img/arrow.png" alt="Another Icon">
        </div>
      </button>
    </div>

    <div class="section2">
      <img src="../../static/task/img/search.png" alt="Search Icon">
      <p>Поиск</p>
      <div class="icons">
        <img src="../../static/task/img/notification.png" alt="First Icon">
        <img src="../../static/task/img/avatar.jpg" alt="Second Icon">
      </div>
    </div>
  </div>
</body>
</html>

task/templates/task/base6.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #232333;
            font-family: Arial, sans-serif;
        }

        .container {
            display: flex;
            justify-content: space-between;
            padding: 20px;
        }

        .left-section {
            background-color: #2B2C40;
            width: 320px;
            height: 800px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            position: relative;
        }

        .logo {
            width: 323px;
            height: 67px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .projects {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            margin-top: 50px;
            display: flex;
            align-items: center;
        }

        .projects img {
            width: 30px;
            height: 30px;
            margin-right: 10px;
        }

        .projects a {
            text-decoration: none;
            color: #A3A4CC;
            font-size: 20px;
            font-weight: bold;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
        }

        .right-section {
            margin-left: 13px;
        }

        .right-rectangle {
            background-color: #2B2C40;
            width: 850px;
            height: 80px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            display: flex;
            align-items: center;
            padding: 0 20px;
        }

        .search {
            display: flex;
            align-items: center;
        }

        .search img {
            width: 30px;
            height: 30px;
            margin-right: 10px;
        }

        .search-text {
            color: #A3A4CC;
            font-size: 32px;
            font-weight: regular;
        }

        .right-icons {
            display: flex;
            justify-content: flex-end;
            margin-left: auto;
        }

        .right-icons img {
            margin-left: 24px;
        }

        .circle-icon {
            width: 35px;
            height: 35px;
            border-radius: 50%;
        }

        .large-circle-icon {
            width: 50px;
            height: 50px;
            border-radius: 50%;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="left-section">
            <img class="logo" src="path/to/your/logo.png" alt="Logo">
            <div class="projects">
                <a href="#">
                    <img src="path/to/your/projects_icon.png" alt="Projects">
                    Проекты
                </a>
                <img src="path/to/your/second_icon.png" alt="Second Icon">
            </div>
        </div>

        <div class="right-section">
            <div class="right-rectangle">
                <div class="search">
                    <img src="path/to/your/search_icon.png" alt="Search Icon">
                    <div class="search-text">Поиск</div>
                </div>
                <div class="right-icons">
                    <img class="circle-icon" src="path/to/your/circle_icon.png" alt="Circle Icon">
                    <img class="large-circle-icon" src="path/to/your/large_circle_icon.png" alt="Large Circle Icon">
                </div>
            </div>
        </div>
    </div>
</body>
</html>

task/templates/task/create_task.html
{% extends 'task/base.html' %}

{% block content %}
  <h2>Create Task for {{ project.name_project }}</h2>
<form method="post" action="{% url 'create_task' project.id %}">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create Task">
</form>
  <a href="{% url 'company_dashboard' %}">Back to Dashboard</a>
{% endblock %}

task/templates/task/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../../static/task/css/styles.css">
</head>
<body>
<header>
    <div class="language-selector">
        <a href="#" class="language-link">RU</a>
        <a href="#" class="language-link">EN</a>
    </div>
    <nav class="main-menu">
        <a href="#">Возможности</a>
        <a href="#">Решения</a>
        <a href="#">Планы</a>
        <a href="#">Поддержка</a>
    </nav>
    <div class="info-icon">
        <img src="../../static/task/img/info.svg" alt="Info">
    </div>
</header>

<div class="auth">
    <div class="auth_item">
        <a href="#">
            <img src="../../static/task/img/Logo.svg" alt="Your Logo" class="logo">
        </a>
        <form method="post" class="login-form">
            {% csrf_token %}
            {{ form.username }}
            <br>
            {{ form.username.errors }}  <!-- Ошибки для поля 'username' -->

            {{ form.password }}
            <br>
            {{ form.password.errors }}

            {% if form.errors %}
            <div class="alert alert-light">
                <strong>Ошибка!</strong> Неверный логин или пароль
            </div>
            {% endif %}
            <button type="submit" class="btn btn-primary">Войти</button>
            <a href="{% url 'registration' %}">Зарегистрироваться</a>
        </form>
    </div>
</div>

<footer>
    <p class="footer-text">Готовы повысить эффективность вашей команды? <a href="{% url 'registration_manager' %}" class="register-link">ЗАРЕГИСТРИРУЙТЕСЬ</a>
    </p>
</footer>

</body>
</html>

task/templates/task/notifications.html
{% extends 'task/base.html' %}

{% block title %}Уведомления{% endblock %}

{% block content %}
    <h2>Уведомления</h2>
    {% for notification in notifications %}
        <div class="{% if notification.is_read %}read{% else %}unread{% endif %}">
            <p>{{ notification.message }}</p>
            <small>{{ notification.timestamp }}</small>
        </div>
    {% endfor %}
{% endblock %}

task/templates/task/project_detail.html
{% extends 'task/base.html' %}
{% block title %}Project Detail{% endblock %}

{% block content %}
  <h1>{{ project.name_project }}</h1>
  <p><strong>Описание:</strong> {{ project.description_project }}</p>
  <p><strong>Дедлайн:</strong> {{ project.start_date }}-{{ project.end_date }}</p>

  <h2>Задачи в этом проекте:</h2>
  <ul>
    {% for task in project.task_set.all %}
      <li>
        <a href="{% url 'task_detail' task.pk %}">{{ task.name_task }}</a>
        {% if task.assigned_developer %}
          (Разработчик: {{ task.assigned_developer.username }})
        {% endif %}
      </li>
    {% endfor %}
  </ul>

  <h2>Разработчики в проекте:</h2>
  <ul>
    {% for task in project.task_set.all %}
      {% if task.assigned_developer %}
        <li>{{ task.assigned_developer.username }}</li>
      {% endif %}
    {% endfor %}
  </ul>

  <a href="{% url 'create_task' project.id %}" role="button" class="btn btn-primary">Создать задачу</a>
{% endblock %}

task/templates/task/send_completed_task.html
{% extends 'task/base.html' %}
{% block title %}Отправить выполненную задачу{% endblock %}
{% block content %}
  <h2>Отправить выполненную задачу</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
{% endblock %}